# Generated by Django 3.2 on 2021-05-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterfit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pants_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
