# Generated by Django 3.2 on 2021-05-30 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betterfit', '0002_user_pants_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pants_img',
        ),
    ]
